import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import { SquircleNoScript } from "@squircle-js/react";
import { Agentation } from "agentation";
import "./globals.css";

// Inter Display, self-hosted from the rsms/inter v4.1 release on GitHub (web/ folder,
// OFL). These are the real Display cuts rather than InterVariable pinned to opsz 32 —
// same design intent, but the optical size is baked into the outlines, so nothing
// depends on a font-variation-settings declaration surviving. Only the three weights
// the app actually asks for are shipped; add a file here before using a fourth.
const interDisplay = localFont({
  src: [
    { path: "./fonts/InterDisplay-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/InterDisplay-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/InterDisplay-SemiBold.woff2", weight: "600", style: "normal" },
  ],
  variable: "--font-inter-display",
  display: "swap",
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${geist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Squircle clip-paths are computed client-side; without this the SSR'd
            `clip-path: path('')` hides squircled elements until hydration. */}
        <SquircleNoScript />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* devDependency — the NODE_ENV gate keeps it out of production bundles,
            where it wouldn't be installed. */}
        {process.env.NODE_ENV === "development" && (
          <Agentation endpoint="http://localhost:4747" />
        )}
      </body>
    </html>
  );
}
