import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { SquircleNoScript } from "@squircle-js/react";
import { Agentation } from "agentation";
import "./globals.css";

// Inter Display is the opsz 32 end of Inter's optical-size axis, so we pull the
// variable font with `opsz` exposed and pin it in globals.css.
const interDisplay = Inter({
  variable: "--font-inter-display",
  subsets: ["latin"],
  axes: ["opsz"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <SquircleNoScript />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* devDependency — the NODE_ENV gate keeps it out of production bundles,
            where it wouldn't be installed. */}
        {process.env.NODE_ENV === "development" && (
          <Agentation endpoint="http://localhost:4747" />
        )}
      </body>
    </html>
  );
}
